// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extension/HeartExtension.proto

package com.randioo.doudizhu_server.protocol;

public final class HeartExtension {
  private HeartExtension() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.randioo.doudizhu_server.protocol.HeartExtension.serverTime);
  }
  public static final int SERVERTIME_FIELD_NUMBER = 1;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.randioo.doudizhu_server.protocol.Heart.SCHeart,
      java.util.List<java.lang.Integer>> serverTime =
        com.google.protobuf.GeneratedMessage
          .newGeneratedExtension();
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036extension/HeartExtension.proto\022$com.ra" +
      "ndioo.doudizhu_server.protocol\032\013Heart.pr" +
      "oto:A\n\nserverTime\022-.com.randioo.doudizhu" +
      "_server.protocol.SCHeart\030\001 \003(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          com.randioo.doudizhu_server.protocol.HeartExtension.serverTime.internalInit(
              com.randioo.doudizhu_server.protocol.HeartExtension.getDescriptor().getExtensions().get(0),
              java.lang.Integer.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.doudizhu_server.protocol.Heart.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
